version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "Tech"

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "Tech"
    groups:
      dev-dependencies:
        dependency-type: development
